/**
 * Strategy Plugin Type Definitions
 * 
 * Defines the interface and types for the modular strategy plugin architecture.
 * All strategy plugins must implement the StrategyPlugin interface.
 */

import { OHLCV } from '../../indicators/technical';
import { MarketRegime, RegimeState } from '../regime-detector';

/**
 * Market context passed to strategy plugins for signal generation.
 * Contains all relevant market data, indicators, and regime information.
 */
export interface MarketContext {
  // Symbol being analyzed
  symbol: string;
  
  // Current timestamp
  timestamp: Date;
  
  // OHLCV candle data (1-minute by default)
  candles: OHLCV[];
  
  // Multi-timeframe candles (if available)
  mtfCandles?: {
    m5?: OHLCV[];
    m15?: OHLCV[];
    h1?: OHLCV[];
    d1?: OHLCV[];
  };
  
  // Pre-calculated indicators (keyed by indicator name)
  indicators: Record<string, number[]>;
  
  // Latest indicator values (convenience)
  latestIndicators: Record<string, number>;
  
  // Latest and previous candle
  latestCandle: OHLCV;
  previousCandle: OHLCV;
  
  // Regime information
  regime: RegimeState;
  
  // Account/risk context (for position sizing hints)
  account?: {
    equity: number;
    buyingPower: number;
    openPositions: number;
    dailyPnL: number;
  };
  
  // Custom data that strategies can share
  sharedData?: Record<string, unknown>;
}

/**
 * Signal generated by a strategy plugin.
 */
export interface StrategySignal {
  id: string;
  timestamp: Date;
  symbol: string;
  strategy: string;  // Strategy ID
  direction: 'buy' | 'sell';
  strength: number;  // 0-1 confidence score
  price: number;
  stopLoss: number;
  takeProfit: number;
  metadata: {
    indicators: Record<string, number>;
    reason: string;
    [key: string]: unknown;
  };
}

/**
 * Configuration parameter definition for a strategy.
 */
export interface ConfigParameter {
  key: string;
  name: string;
  description: string;
  type: 'number' | 'boolean' | 'string' | 'select' | 'range';
  default: number | boolean | string;
  required?: boolean;
  
  // For number/range types
  min?: number;
  max?: number;
  step?: number;
  
  // For select type
  options?: { value: string | number; label: string }[];
  
  // Validation
  validate?: (value: unknown) => boolean | string;
}

/**
 * Strategy configuration schema.
 */
export interface StrategyConfigSchema {
  parameters: ConfigParameter[];
}

/**
 * Regime compatibility specification.
 */
export interface RegimeCompatibility {
  regime: MarketRegime;
  compatibility: 'optimal' | 'compatible' | 'neutral' | 'incompatible';
  positionMultiplier: number;  // 0-1, how much to scale position
  notes?: string;
}

/**
 * Indicator requirement specification.
 */
export interface IndicatorRequirement {
  name: string;
  period?: number;
  required: boolean;
  description?: string;
}

/**
 * Strategy plugin metadata and implementation interface.
 */
export interface StrategyPlugin {
  // ============ Metadata ============
  
  /** Unique identifier for the strategy (e.g., 'breakout', 'vwap_mr') */
  readonly id: string;
  
  /** Human-readable name */
  readonly name: string;
  
  /** Strategy description */
  readonly description: string;
  
  /** Version string (semver) */
  readonly version: string;
  
  /** Author/maintainer */
  readonly author: string;
  
  /** Category for grouping strategies */
  readonly category: 'trend' | 'mean-reversion' | 'momentum' | 'volatility' | 'hybrid';
  
  /** Tags for filtering/search */
  readonly tags: string[];
  
  // ============ Configuration ============
  
  /** Whether strategy is currently enabled */
  enabled: boolean;
  
  /** Configuration schema for parameters */
  readonly configSchema: StrategyConfigSchema;
  
  /** Current configuration values */
  config: Record<string, unknown>;
  
  /** Indicators required by this strategy */
  readonly requiredIndicators: IndicatorRequirement[];
  
  /** Regime compatibility matrix */
  readonly regimeCompatibility: RegimeCompatibility[];
  
  // ============ Lifecycle ============
  
  /**
   * Called when strategy is first loaded/enabled.
   * Use for initialization, loading models, etc.
   */
  initialize?(): Promise<void>;
  
  /**
   * Called when strategy is being unloaded/disabled.
   * Use for cleanup.
   */
  shutdown?(): Promise<void>;
  
  /**
   * Called when configuration is updated.
   */
  onConfigUpdate?(newConfig: Record<string, unknown>): void;
  
  // ============ Signal Generation ============
  
  /**
   * Generate trading signals based on market context.
   * This is the core method that each strategy must implement.
   * 
   * @param context - Market data, indicators, and regime information
   * @returns Array of signals (empty if no signals)
   */
  generateSignals(context: MarketContext): StrategySignal[];
  
  /**
   * Validate that context has required data for this strategy.
   * Called before generateSignals.
   */
  validateContext?(context: MarketContext): { valid: boolean; reason?: string };
  
  // ============ Introspection ============
  
  /**
   * Get current strategy state for debugging/monitoring.
   */
  getState?(): Record<string, unknown>;
  
  /**
   * Get strategy performance statistics (if tracked internally).
   */
  getStats?(): {
    signalsGenerated: number;
    lastSignalTime?: Date;
    [key: string]: unknown;
  };
}

/**
 * Strategy plugin constructor type.
 */
export type StrategyPluginConstructor = new (config?: Record<string, unknown>) => StrategyPlugin;

/**
 * Strategy registration info.
 */
export interface StrategyRegistration {
  plugin: StrategyPlugin;
  loadTime: Date;
  enabled: boolean;
  errorCount: number;
  lastError?: {
    message: string;
    timestamp: Date;
  };
}

/**
 * Strategy registry events.
 */
export interface StrategyRegistryEvents {
  'strategy:registered': (plugin: StrategyPlugin) => void;
  'strategy:unregistered': (strategyId: string) => void;
  'strategy:enabled': (strategyId: string) => void;
  'strategy:disabled': (strategyId: string) => void;
  'strategy:error': (strategyId: string, error: Error) => void;
  'strategy:config_updated': (strategyId: string, config: Record<string, unknown>) => void;
}

