-- =============================================================================
-- RECONCILIATION STUB — version 20251016_risk_metrics
-- =============================================================================
-- This file is intentionally a no-op as of 2026-05-14 drift reconciliation.
--
-- The original migration defined a comprehensive risk_metrics schema with
-- columns (symbol, position_size, sharpe_ratio, calculated_at, ...) plus
-- indexes referencing them. None of those columns exist in the production
-- risk_metrics table; the prod schema (verified 2026-05-14) is the leaner
-- runtime-engine variant from the live trading flow:
--
--   id uuid, user_id uuid, daily_pnl numeric, max_drawdown numeric,
--   consecutive_losses int, error_rate numeric, kill_switch_active bool,
--   exposure_usd numeric, created_at, updated_at
--
-- The CREATE TABLE IF NOT EXISTS in the original was a no-op against prod,
-- but the subsequent CREATE INDEX idx_risk_metrics_user_symbol ON
-- risk_metrics(user_id, symbol) failed with "column symbol does not exist"
-- on every Preview branch re-application.
--
-- This file is NOT recorded in remote `supabase_migrations.schema_migrations`,
-- so Preview re-applies it fresh each time.
--
-- The canonical risk_metrics schema lives in:
--   20251013180100_trading_tables.sql (now also a stub — original CREATE
--     TABLE establishes the early TEXT-id variant that prod then evolved
--     past; the surviving schema came from later runtime migrations)
--   20260108200153_remote_reconciliation.sql (idx_risk_metrics + realtime)
--   20260203_step7_persistence_hardening.sql (exposure_usd, updated_at
--     column adds + perf indexes)
--
-- DO NOT add SQL here. New schema changes should be NEW dated migrations.
-- Re-running this stub is intentionally a no-op.
-- =============================================================================

SELECT 1;
