-- =============================================================================
-- RECONCILIATION STUB — version 20251013180100_trading_tables
-- =============================================================================
-- This file is intentionally a no-op as of 2026-05-14 drift reconciliation.
--
-- The original migration defined CREATE TABLE / CREATE INDEX / CREATE POLICY /
-- CREATE TRIGGER for trades, positions, orders, risk_metrics, daily_equity,
-- and audit_log. None of those table definitions were the schema actually
-- deployed to production:
--
--   * positions/orders use UUID ids per 20251013054024_remote_reconciliation
--     (which DROP TABLE CASCADE then CREATE TABLE with the canonical schema)
--   * indexes (idx_positions_symbol, idx_positions_updated_at, etc.) collide
--     with the index set actually applied via the dashboard, captured in
--     20260108200153_remote_reconciliation.sql
--   * RLS policies named "Service role full access" are superseded by the
--     {table}_rw_own / {table}_service_policy patterns from later pulled
--     reconciliation files
--   * triggers reference an `updated_at` column that doesn't exist on the
--     real positions schema
--
-- This file is NOT recorded in remote `supabase_migrations.schema_migrations`,
-- so Supabase Preview re-applies it on every branch creation. Keeping the
-- original DDL caused the Preview check to fail with "column updated_at does
-- not exist" / "relation already exists" errors.
--
-- The canonical schema for these tables lives in (and stays applied via):
--   20251013051846_remote_reconciliation.sql (initial table creates)
--   20251013054024_remote_reconciliation.sql (drop+recreate to canonical)
--   20260108200153_remote_reconciliation.sql (performance indexes + realtime)
--   20260202192520_remote_reconciliation.sql (RLS policy reconciliation)
--   20260204214734..220632 (proxy-only writes, security-invoker views,
--     RLS policy name reconcile, perf index cleanup)
--
-- DO NOT add SQL here. New schema changes should be NEW dated migrations.
-- Re-running this stub is intentionally a no-op.
-- =============================================================================

SELECT 1;
