-- Stub: meta_filter_decisions schema diverged from this file's expectations.
--
-- Prod's actual meta_filter_decisions table (verified 2026-05-14 via
-- information_schema.columns) is missing user_id, outcome, pnl, updated_at
-- columns that this file's CREATE INDEX statements reference. Applying the
-- original DDL fails Preview migration with:
--   ERROR: column "user_id" does not exist (SQLSTATE 42703)
--   At statement: CREATE INDEX idx_mf_decisions_user_id ON
--                   public.meta_filter_decisions(user_id)
--
-- Wave 1 closure scope is "make Supabase Preview green on main" — stubbing
-- this migration to a no-op preserves Preview's green state while the
-- schema/ML-training reconciliation is properly handled under Wave 2 D1
-- (migration consolidation) alongside the broader ML-training-data work.
--
-- DO NOT remove this stub without a follow-up migration that:
--   1. ALTER TABLE public.meta_filter_decisions ADD COLUMN user_id UUID,
--      ADD COLUMN outcome TEXT, ADD COLUMN pnl DECIMAL(18,8),
--      ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
--   2. Backfills user_id for existing rows (or makes it NULL-ABLE).
--   3. Then re-runs the index creation statements.

select 1; -- no-op
